import { Colors, Fonts } from "@/constants/Style.data";
import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    header: {
        marginTop: 40,
        paddingHorizontal: 20,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 20,
    },
    headerText: {
        fontFamily: Fonts.PoppinsBold,
        fontSize: 25,
        color: Colors.white,
    },
    container: {
        backgroundColor: Colors.white,
        flex: 1,
        borderTopLeftRadius: 60,
        borderTopRightRadius: 60,
        padding: 20,
        paddingTop: 40,
        marginTop: 120,
        justifyContent: 'space-between',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    avatarBox: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: -120, // Move the avatar up
    },
    text: {
        fontFamily: Fonts.PoppinsRegular,
        fontSize: 18,
        lineHeight: 24,
    },
    textName: {
        fontFamily: Fonts.PoppinsBold,
        fontSize: 35,
        lineHeight: 38,
        color: '#000',
        width: 250,
        textAlign: 'center',
    },
    textNameEditing: {
        fontFamily: Fonts.PoppinsBold,
        fontSize: 35,
        lineHeight: 38,
        color: '#000',
        backgroundColor: Colors.lightGray,
        width: 250,
        textAlign: 'center',
        borderRadius: 10,
    },
    avatar: {
        width: 200,
        height: 200,
        borderRadius: 100,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.white,
        borderWidth: 1,
        borderColor: Colors.white,
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
    },
    avatarImage:{
        width: '100%',
        height: '100%',
        borderRadius: 100,
    },
    info: {
        alignItems: 'center',
        marginTop: 20,
        width: '100%',
    },
    nameEdit: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        marginBottom: 10,
    },
    Edit: {
        position: 'absolute',
        right: 10,
    },
    status: {
        backgroundColor: Colors.green,
        paddingHorizontal: 20,
        paddingVertical: 5,
        borderRadius: 20,
        marginTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
    },
    statusOff: {
        backgroundColor: Colors.red,
        paddingHorizontal: 20,
        paddingVertical: 5,
        borderRadius: 20,
        marginTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    statusOption: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginTop: 10,
        width: 180,
        padding: 15,
        borderRadius: 10,
        backgroundColor: Colors.white,
        elevation: 10,
    },
    statusOptionOn: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: Colors.green,
    },
    statusOptionOff: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: Colors.red,
    },
    logoutButton:{
        flexDirection: 'row',
        backgroundColor: Colors.red,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 15,
        borderRadius: 10,
        marginBottom: 20,
        gap: 10,
    },
    logoutText: {
        fontFamily: Fonts.PoppinsBold,
        fontSize: 18,
        color: Colors.white,
    }
})